# Use dbadmin/dbpassword as user/password credentials
version: '3.1'

services:

  # MongoDB database
  mongo:
    image: mongo:7.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: dbpassword
      MONGO_INITDB_DATABASE: userdb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
        - 27017:27017